### ISSUE TITLE
Security vulnerability - Prototype Pollution - Bump requirejs to version 2.3.7 or latest

### ISSUE THREAD

**Issue by anaarezo** [dependents/node-module-lookup-amd#40]
I've identified a security vulnerability in the requirejs library that is currently impacting the security of a project I am involved with. The specific issue is addressed in version 2.3.7 of requirejs. To mitigate the potential security risks, would you mind to update the requirejs dependency in our project to version 2.3.7 or latest? 

Here is a link for reference of the problem:
https://security.snyk.io/vuln/SNYK-JS-REQUIREJS-5416713

Thanks.

**Comment by XhmikosR** [comment]
https://github.com/dependents/node-module-lookup-amd/releases/tag/v9.0.2
